openapi: 3.0.2
info:
  version: 0.1.0
  title: Tool Registry API
  contact:
    name: The Tool Registry Team
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://github.com/Sage-Bionetworks/tool-registry-schemas'
  license:
    name: Apache 2.0
    url: 'https://github.com/Sage-Bionetworks/tool-registry-schemas'
  x-logo:
    url: 'https://Sage-Bionetworks.github.io/tool-registry-schemas/logo.png'
  description: >
    The OpenAPI specification implemented by the Tool Registry.

    # Overview

    TBA
tags:
  - name: Tool
    description: Operations about tools
  - name: Tag
    description: Operations about tags

servers:
  - url: "{protocol}://tool-registry.org/api/v1"
    variables:
      protocol:
        enum:
          - http
          - https
        default: https

paths:
  /tags:
    $ref: paths/tags.yaml
  /tags/{tagId}:
    $ref: paths/tags@{tagId}.yaml
  /tools:
    $ref: 'paths/tools.yaml'
  /tools/{toolId}:
    $ref: 'paths/tools@{toolId}.yaml'