openapi: 3.0.2
info:
  version: 0.1.0
  title: Tool Registry API
  contact:
    name: The Tool Registry Team
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://github.com/Sage-Bionetworks/tool-registry-schemas'
  license:
    name: Apache 2.0
    url: >-
      https://github.com/Sage-Bionetworks/tool-registry-schemas/blob/develop/LICENSE
  x-logo:
    url: 'https://Sage-Bionetworks.github.io/tool-registry-schemas/logo.png'
  description: |
    The OpenAPI specification implemented by the Tool Registry.
    # Overview
    TBA
tags:
  - name: Tool
    description: Operations about tools
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /tools:
    post:
      tags:
        - Tool
      summary: Add a tool
      description: Add a tool
      operationId: createTool
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tool'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
          description: Success
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
    get:
      tags:
        - Tool
      summary: List the tools in the registry
      description: Returns the tools in the registry
      operationId: listTools
      parameters:
        - in: query
          name: limit
          description: Maximum number of results returned
          required: false
          schema:
            type: integer
            default: 10
            minimum: 10
            maximum: 100
        - in: query
          name: offset
          description: Index of the first result that must be returned
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfTools'
          description: Success
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    ResponsePageMetadata:
      type: object
      description: A page of results
      properties:
        offset:
          description: Index of the first result that must be returned
          type: integer
        limit:
          description: Maximum number of results returned
          type: integer
        links:
          description: Links to navigate to different pages of results
          type: object
          properties:
            next:
              description: Link to the next page of results
              type: string
              format: uri
      required:
        - offset
        - limit
        - links
    Tool:
      type: object
      description: A tool
      properties:
        id:
          description: The ID of the tool
          type: string
          readOnly: true
        name:
          description: The tool name
          type: string
          minLength: 3
          maxLength: 60
          pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
          example: awesome-tool
        version:
          description: The version of the tool (SemVer string)
          type: string
          minLength: 1
          pattern: >-
            ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          example: 1.0.0
        license:
          description: The license of this service (spdx.org/licenses Identifier)
          type: string
          enum:
            - afl-3.0
            - apache-2.0
            - artistic-2.0
            - bsl-1.0
            - bsd-2-clause
            - bsd-3-clause
            - bsd-3-clause-clear
            - cc
            - cc0-1.0
            - cc-by-4.0
            - cc-by-sa-4.0
            - wtfpl
            - ecl-2.0
            - epl-1.0
            - epl-2.0
            - eupl-1.1
            - agpl-3.0
            - gpl
            - gpl-2.0
            - gpl-3.0
            - lgpl
            - lgpl-2.1
            - lgpl-3.0
            - isc
            - lppl-1.3c
            - ms-pl
            - mit
            - mpl-2.0
            - osl-3.0
            - postgresql
            - ofl-1.1
            - ncsa
            - unlicense
            - zlib
          example: apache-2.0
        repository:
          description: The place where the code lives
          type: string
          example: 'github:awesome-org/awesome-tool'
        description:
          description: 'A short, one-sentence summary of the service'
          type: string
          maxLength: 100
          example: An awesome tool that returns 42
        author:
          description: The author of the tool
          type: string
          example: Example Author
        authorEmail:
          description: The email address of the author
          type: string
          format: email
          example: author@example.com
        url:
          description: The URL to the homepage of the tool
          type: string
          format: uri
    PageOfTools:
      type: object
      description: A page of Tools
      allOf:
        - $ref: '#/components/schemas/ResponsePageMetadata'
        - type: object
          properties:
            patients:
              description: An array of Tools
              type: array
              items:
                $ref: '#/components/schemas/Tool'
    Error:
      type: object
      description: Problem details (tools.ietf.org/html/rfc7807)
      properties:
        title:
          type: string
          description: A human readable documentation for the problem type
        status:
          type: integer
          description: The HTTP status code
        detail:
          type: string
          description: >-
            A human readable explanation specific to this occurrence of the
            problem
        type:
          type: string
          description: An absolute URI that identifies the problem type
      required:
        - title
        - status
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: The request conflicts with current state of the target resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
